version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: translator_user
      POSTGRES_PASSWORD: translator_password
      POSTGRES_DB: translator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  translator-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translator-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/translator_db
      SPRING_DATASOURCE_USERNAME: translator_user #Not implemented
      SPRING_DATASOURCE_PASSWORD: translator_password #Not implemented

volumes:
  postgres_data:
